# Generated by Django 5.0.4 on 2024-04-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bansalstore', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
        ),
    ]
