# Generated by Django 5.0.4 on 2024-04-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bansalstore', '0008_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
