# Generated by Django 5.0.4 on 2024-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bansalstore', '0009_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
