# Generated by Django 5.0.4 on 2024-05-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bansalstore', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
